from __future__ import annotations

import os
import sqlite3
import sys
from pathlib import Path
from typing import Any

import psycopg

ROOT = Path(__file__).resolve().parents[1]
SQLITE_PATH = Path(os.getenv("SQLITE_PATH", str(ROOT / "data" / "chat.sqlite3")))
DATABASE_URL = os.getenv("DATABASE_URL")

TABLES = {
    "avatars": [
        "id",
        "label",
        "filename",
        "content_type",
        "file_size",
        "active",
        "sort_order",
        "created_at",
    ],
    "users": [
        "id",
        "device_id",
        "nickname",
        "status",
        "ip_hash",
        "created_at",
        "updated_at",
        "last_seen_at",
        "avatar_id",
        "protected",
    ],
    "messages": [
        "id",
        "user_id",
        "nickname",
        "text",
        "mood",
        "sent_at",
        "revoked_at",
        "avatar_id",
        "avatar_label",
        "avatar_filename",
    ],
    "private_messages": [
        "id",
        "sender_id",
        "recipient_id",
        "sender_nickname",
        "recipient_nickname",
        "text",
        "mood",
        "avatar_id",
        "avatar_label",
        "avatar_filename",
        "sent_at",
        "revoked_at",
    ],
    "bans": [
        "id",
        "device_id",
        "ip_hash",
        "reason",
        "created_at",
    ],
    "room_state": [
        "key",
        "value",
    ],
}

POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id TEXT NOT NULL UNIQUE,
  nickname TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('pending', 'approved', 'rejected', 'banned')),
  ip_hash TEXT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  last_seen_at BIGINT NOT NULL,
  avatar_id BIGINT,
  protected INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS messages (
  id TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  nickname TEXT NOT NULL,
  text TEXT NOT NULL,
  mood TEXT NOT NULL,
  sent_at BIGINT NOT NULL,
  revoked_at BIGINT,
  avatar_id BIGINT,
  avatar_label TEXT,
  avatar_filename TEXT
);

CREATE TABLE IF NOT EXISTS private_messages (
  id TEXT PRIMARY KEY,
  sender_id BIGINT NOT NULL REFERENCES users(id),
  recipient_id BIGINT NOT NULL REFERENCES users(id),
  sender_nickname TEXT NOT NULL,
  recipient_nickname TEXT NOT NULL,
  text TEXT NOT NULL,
  mood TEXT NOT NULL,
  avatar_id BIGINT,
  avatar_label TEXT,
  avatar_filename TEXT,
  sent_at BIGINT NOT NULL,
  revoked_at BIGINT
);

CREATE TABLE IF NOT EXISTS bans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id TEXT,
  ip_hash TEXT,
  reason TEXT,
  created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS room_state (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS avatars (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL,
  filename TEXT NOT NULL UNIQUE,
  content_type TEXT NOT NULL,
  file_size BIGINT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL
);
"""


def sqlite_columns(conn: sqlite3.Connection, table: str) -> set[str]:
    return {row["name"] for row in conn.execute(f"PRAGMA table_info({table})")}


def table_exists(conn: sqlite3.Connection, table: str) -> bool:
    row = conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?",
        (table,),
    ).fetchone()
    return bool(row)


def existing_count(pg: psycopg.Connection[Any], table: str) -> int:
    with pg.cursor() as cur:
        cur.execute(f"SELECT COUNT(*) FROM {table}")
        return int(cur.fetchone()[0])


def migrate_table(sqlite: sqlite3.Connection, pg: psycopg.Connection[Any], table: str, columns: list[str]) -> int:
    if not table_exists(sqlite, table):
        return 0
    available = sqlite_columns(sqlite, table)
    selected = [column for column in columns if column in available]
    rows = sqlite.execute(f"SELECT {', '.join(selected)} FROM {table}").fetchall()
    if not rows:
        return 0

    placeholders = ", ".join(["%s"] * len(selected))
    update_columns = [column for column in selected if column != selected[0]]
    updates = ", ".join(f"{column} = EXCLUDED.{column}" for column in update_columns)
    conflict_target = "key" if table == "room_state" else "id"
    sql = (
        f"INSERT INTO {table} ({', '.join(selected)}) VALUES ({placeholders}) "
        f"ON CONFLICT ({conflict_target}) DO UPDATE SET {updates}"
    )

    with pg.cursor() as cur:
        for row in rows:
            cur.execute(sql, tuple(row[column] for column in selected))
    return len(rows)


def reset_identity(pg: psycopg.Connection[Any], table: str) -> None:
    if table == "room_state":
        return
    with pg.cursor() as cur:
        cur.execute(
            """
            SELECT pg_get_serial_sequence(%s, 'id')
            """,
            (table,),
        )
        sequence = cur.fetchone()[0]
        if sequence:
            cur.execute(
                f"SELECT setval(%s, COALESCE((SELECT MAX(id) FROM {table}), 1), true)",
                (sequence,),
            )


def main() -> int:
    print("Starting SQLite -> Supabase migration...")
    if not DATABASE_URL:
        print("Missing DATABASE_URL environment variable.", file=sys.stderr)
        return 1
    if not SQLITE_PATH.exists():
        print(f"SQLite database not found: {SQLITE_PATH}", file=sys.stderr)
        return 1

    sqlite = sqlite3.connect(f"file:{SQLITE_PATH}?mode=ro", uri=True)
    sqlite.row_factory = sqlite3.Row
    with sqlite, psycopg.connect(DATABASE_URL) as pg:
        print("Connected to Supabase Postgres.")
        for statement in POSTGRES_SCHEMA.split(";"):
            if statement.strip():
                pg.execute(statement)
        print("Ensured Supabase tables exist.")

        print(f"SQLite source: {SQLITE_PATH}")
        for table, columns in TABLES.items():
            before = existing_count(pg, table)
            migrated = migrate_table(sqlite, pg, table, columns)
            after = existing_count(pg, table)
            reset_identity(pg, table)
            print(f"{table}: migrated {migrated}, rows before {before}, rows after {after}")
        pg.commit()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
